steps:
  - label: ':hammer: Build Nomad x64'
    command: './build.sh'
    plugins:
      docker-login#v2.0.0:
        username: devopsintralox
        password-env: DOCKER_LOGIN_PASSWORD
    agents:
      arch: "x86"
      
  - label: ':hammer: Build Nomad-gpu x64'
    command: './build-gpu.sh'
    plugins:
      docker-login#v2.0.0:
        username: devopsintralox
        password-env: DOCKER_LOGIN_PASSWORD
    agents:
      arch: "x86"

  - label: ':hammer: Build Docker Community Overloads Nomad Arm64'
    command: './build_arm64_nomad.sh'
    plugins:
      docker-login#v2.0.0:
        username: devopsintralox
        password-env: DOCKER_LOGIN_PASSWORD
    agents:
      arch: "arm64"

  - label: ':hammer: Build Docker Community Overloads Consul Arm64'
    command: './build_arm64_consul.sh'
    plugins:
      docker-login#v2.0.0:
        username: devopsintralox
        password-env: DOCKER_LOGIN_PASSWORD
    agents:
      arch: "arm64"
